src/LeadsManager/Controllers/EmailUsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LeadsManager.Data;
using LeadsManager.Models;
using System.Xml.Linq;

namespace LeadsManager.Controllers
{
    public class EmailUsController : Controller
    {
        private readonly LeadsContext _context;
        private ToXml toXml = new ToXml();

        public EmailUsController(LeadsContext context)
        {
            _context = context;    
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.EmailUs.ToListAsync());
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emailUs = await _context.EmailUs.SingleOrDefaultAsync(m => m.id == id);
            if (emailUs == null)
            {
                return NotFound();
            }

            return View(emailUs);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,DateSynced,IsSynced,dropdown_list_field_controller,pragraph_text_field_controller,text_field_controller,text_field_controller_0,text_field_controller_1,text_field_controller_2")] EmailUs emailUs)
        {
            if (ModelState.IsValid)
            {
                emailUs.id = Guid.NewGuid();
                _context.Add(emailUs);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(emailUs);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emailUs = await _context.EmailUs.SingleOrDefaultAsync(m => m.id == id);
            if (emailUs == null)
            {
                return NotFound();
            }
            return View(emailUs);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("id,DateSynced,IsSynced,dropdown_list_field_controller,pragraph_text_field_controller,text_field_controller,text_field_controller_0,text_field_controller_1,text_field_controller_2")] EmailUs emailUs)
        {
            if (id != emailUs.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(emailUs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmailUsExists(emailUs.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(emailUs);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emailUs = await _context.EmailUs.SingleOrDefaultAsync(m => m.id == id);
            if (emailUs == null)
            {
                return NotFound();
            }

            return View(emailUs);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var emailUs = await _context.EmailUs.SingleOrDefaultAsync(m => m.id == id);
            _context.EmailUs.Remove(emailUs);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool EmailUsExists(Guid id)
        {
            return _context.EmailUs.Any(e => e.id == id);
        }

        public async Task<IActionResult> BuildXml(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            EmailUs emailUs = await _context.EmailUs.SingleOrDefaultAsync(x => x.id == id);

            if (emailUs == null)
            {
                return NotFound();
            }

            var xmlify = toXml.BuildFormXml(emailUs);
            ViewBag.Xml = xmlify.ToString(SaveOptions.DisableFormatting);

            return View(emailUs);
        }
    }
}

src/LeadsManager/Controllers/InquiriesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LeadsManager.Data;
using LeadsManager.Models;
using System.Xml.Linq;

namespace LeadsManager.Controllers
{
    public class InquiriesController : Controller
    {
        private readonly LeadsContext _context;
        private ToXml toXml = new ToXml();

        public InquiriesController(LeadsContext context)
        {
            _context = context;    
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Inquiry.ToListAsync());
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inquiry = await _context.Inquiry.SingleOrDefaultAsync(m => m.id == id);
            if (inquiry == null)
            {
                return NotFound();
            }

            return View(inquiry);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,DateSynced,IsSynced,ad_type,apartment_number,city,confirm_email,country,diploma_or_ged,email_address,evaluation,first_name,how_did_you_hear,how_soon_start,last_name,maiden_name,middle_name,military,name_of_event,other_country,previously_attended,primary_phone,primary_phone_type,program_concentration,program_degree,programs_interested,referral_employer,referral_other_employer,referral_other_school,referral_school,referral_source,referred_by,referred_by_whom,secondary_phone,secondary_phone_type,state_name,street_address,stte,suffix,zip_code")] Inquiry inquiry)
        {
            if (ModelState.IsValid)
            {
                inquiry.id = Guid.NewGuid();
                _context.Add(inquiry);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(inquiry);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inquiry = await _context.Inquiry.SingleOrDefaultAsync(m => m.id == id);
            if (inquiry == null)
            {
                return NotFound();
            }
            return View(inquiry);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("id,DateSynced,IsSynced,ad_type,apartment_number,city,confirm_email,country,diploma_or_ged,email_address,evaluation,first_name,how_did_you_hear,how_soon_start,last_name,maiden_name,middle_name,military,name_of_event,other_country,previously_attended,primary_phone,primary_phone_type,program_concentration,program_degree,programs_interested,referral_employer,referral_other_employer,referral_other_school,referral_school,referral_source,referred_by,referred_by_whom,secondary_phone,secondary_phone_type,state_name,street_address,stte,suffix,zip_code")] Inquiry inquiry)
        {
            if (id != inquiry.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(inquiry);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InquiryExists(inquiry.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(inquiry);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inquiry = await _context.Inquiry.SingleOrDefaultAsync(m => m.id == id);
            if (inquiry == null)
            {
                return NotFound();
            }

            return View(inquiry);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var inquiry = await _context.Inquiry.SingleOrDefaultAsync(m => m.id == id);
            _context.Inquiry.Remove(inquiry);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool InquiryExists(Guid id)
        {
            return _context.Inquiry.Any(e => e.id == id);
        }

        public async Task<IActionResult> BuildXml(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Inquiry inquiry = await _context.Inquiry.SingleOrDefaultAsync(x => x.id == id);

            if (inquiry == null)
            {
                return NotFound();
            }

            var xmlify = toXml.BuildFormXml(inquiry);
            ViewBag.Xml = xmlify.ToString(SaveOptions.DisableFormatting);

            return View(inquiry);
        }
    }
}

src/LeadsManager/Controllers/TalismaController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LeadsManager.Models;
using LeadsManager.Data;

namespace LeadsManager.Controllers
{
    public class TalismaController : Controller
    {
        private readonly TalismaContext _context;

        public TalismaController(TalismaContext context)
        {
            _context = context;    
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Talisma.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var talisma = await _context.Talisma.SingleOrDefaultAsync(m => m.aSyncMailID == id);
            if (talisma == null)
            {
                return NotFound();
            }

            return View(talisma);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("aSyncMailID,bHasAttachment,mMsgContent,nAliasID,nDeliveryStatus,nEventID,nLanguageID,nMailType,nTeamID,tBcc,tCc,tFrom,tSubject,tTo")] Talisma talisma)
        {
            if (ModelState.IsValid)
            {
                _context.Add(talisma);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(talisma);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var talisma = await _context.Talisma.SingleOrDefaultAsync(m => m.aSyncMailID == id);
            if (talisma == null)
            {
                return NotFound();
            }
            return View(talisma);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("aSyncMailID,bHasAttachment,mMsgContent,nAliasID,nDeliveryStatus,nEventID,nLanguageID,nMailType,nTeamID,tBcc,tCc,tFrom,tSubject,tTo")] Talisma talisma)
        {
            if (id != talisma.aSyncMailID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(talisma);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TalismaExists(talisma.aSyncMailID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(talisma);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var talisma = await _context.Talisma.SingleOrDefaultAsync(m => m.aSyncMailID == id);
            if (talisma == null)
            {
                return NotFound();
            }

            return View(talisma);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var talisma = await _context.Talisma.SingleOrDefaultAsync(m => m.aSyncMailID == id);
            _context.Talisma.Remove(talisma);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool TalismaExists(int id)
        {
            return _context.Talisma.Any(e => e.aSyncMailID == id);
        }
    }
}

src/LeadsManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Leads Manager</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/css/bootstrap-override.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link href="~/css/bootstrap-override.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Home</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            Undergrad Forms <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="OpenHouses" asp-action="Index">Open House</a></li>
                            <li><a asp-area="" asp-controller="Inquiries" asp-action="Index">Inquiry</a></li>
                            <li><a asp-area="" asp-controller="Applications" asp-action="Index">Application</a></li>
                        </ul>
                    </li>
                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            Landing Pages <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="LandingPages" asp-action="Index">Landing Pages</a></li>
                        </ul>
                    </li>
                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            Mini forms <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="EmailUs" asp-action="Index">Email Us</a></li>
                            <li><a asp-area="" asp-controller="QuestionForUs" asp-action="Index">Question For Us</a></li>
                            <li><a asp-area="" asp-controller="ReferAFriend" asp-action="Index">Refer A Friend</a></li>
                        </ul>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Talisma" asp-action="Index">Talisma</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Peirce College Leads Manager</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/clipboard/dist/clipboard.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/lib/clipboard/dist/clipboard.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>